// AI Coach tab: builds a Markdown context file from the user's profile +
// last-30-day logs. The user copies a ready-made coach prompt and shares
// the file into the AI chat of their choice (ChatGPT, Claude, etc.).
// Nothing AI-related runs inside this app — no API keys, no servers.

import React, { useCallback, useState } from 'react';
import { Alert, ScrollView, Text, TouchableOpacity, View, StyleSheet } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import * as Clipboard from 'expo-clipboard';
import * as Sharing from 'expo-sharing';
import { cacheDirectory, writeAsStringAsync } from 'expo-file-system/legacy';
import { getExportData } from '../db';
import type { ExportData } from '../db';
import { DIET_LABELS } from '../types';
import { COLORS, common } from '../theme';

function fmtDateTime(iso: string): string {
  const d = new Date(iso);
  return `${d.toLocaleDateString()} ${d.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}`;
}

/** The Markdown context file: profile + trailing-30-day summary. */
function buildContextMarkdown(data: ExportData): string {
  const { profile, allergies, conditions, medications, supplements, counts30, rangeLabel } = data;
  const lines: string[] = [];
  const list = (items: string[]) => (items.length > 0 ? items.map((i) => `- ${i}`).join('\n') : '- None recorded');

  lines.push('# Diet Coach — AI Context File');
  lines.push(`_Exported ${new Date().toLocaleString()}_`);
  lines.push('');
  lines.push('## Profile');
  lines.push(`- **Diet type:** ${DIET_LABELS[profile.diet_type]}`);
  lines.push(`- **Diet nuances:** ${profile.diet_nuances || 'Not specified'}`);
  lines.push(`- **Goals:** ${profile.goals || 'Not specified'}`);
  lines.push(`- **Allergies:** ${allergies.map((a) => a.name).join(', ') || 'None recorded'}`);
  lines.push(`- **Health conditions:** ${conditions.map((c) => c.name).join(', ') || 'None recorded'}`);
  lines.push(
    `- **Medications:** ${medications.map((m) => `${m.name}${m.dosage ? ` (${m.dosage})` : ''} — ${m.times_per_day}x/day`).join('; ') || 'None recorded'}`,
  );
  lines.push(
    `- **Supplements:** ${supplements.map((s) => `${s.name}${s.dosage ? ` (${s.dosage})` : ''} — ${s.times_per_day}x/day`).join('; ') || 'None recorded'}`,
  );
  lines.push('');
  lines.push(`## Last 30 days (${rangeLabel})`);
  lines.push(`- Meals logged: ${counts30.meals}`);
  lines.push(`- Medication doses taken: ${counts30.medsTaken}`);
  lines.push(`- Symptoms logged: ${counts30.symptoms}`);
  lines.push(`- Supplements logged: ${counts30.supplements}`);
  lines.push('');

  if (data.recentMeals.length > 0) {
    lines.push('### Recent meals');
    for (const m of data.recentMeals) {
      lines.push(`- ${fmtDateTime(m.logged_at)} — ${m.meal_type}: ${m.name}${m.notes ? ` (${m.notes})` : ''}`);
    }
    lines.push('');
  }
  if (data.recentSymptoms.length > 0) {
    lines.push('### Recent symptoms');
    for (const s of data.recentSymptoms) {
      lines.push(`- ${fmtDateTime(s.logged_at)} — ${s.name} (severity ${s.severity}/5)${s.notes ? ` (${s.notes})` : ''}`);
    }
    lines.push('');
  }
  if (data.recentSupplements.length > 0) {
    lines.push('### Recent supplements');
    for (const s of data.recentSupplements) {
      lines.push(`- ${fmtDateTime(s.logged_at)} — ${s.name}${s.notes ? ` (${s.notes})` : ''}`);
    }
    lines.push('');
  }
  if (data.recentMeds.length > 0) {
    lines.push('### Recent medication doses');
    for (const m of data.recentMeds) {
      lines.push(`- ${fmtDateTime(m.taken_at)} — ${m.medication_name} taken`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by Diet Coach. Share this file with your preferred AI chat along with the coach setup prompt._');
  return lines.join('\n');
}

/** The ready-to-paste prompt that turns any AI chat into the user's coach. */
function buildCoachPrompt(data: ExportData): string {
  const dietLabel = DIET_LABELS[data.profile.diet_type];
  return (
    `You are my ${dietLabel} diet coach. I am about to share a Markdown file with my diet profile ` +
    `(diet type, personal nuances, allergies, health conditions, medications, supplements) and my food, symptom, ` +
    `supplement, and medication logs from the last 30 days.\n\n` +
    `Use that context to:\n` +
    `1. Suggest tweaks to my diet that fit my ${dietLabel} approach and restrictions.\n` +
    `2. Give me meal ideas I will actually enjoy.\n` +
    `3. Point out any patterns you notice between what I eat and how I feel.\n\n` +
    `Important: you are not a medical professional and this is not medical advice. ` +
    `Never tell me to start, stop, or change any medication — only my doctor can do that. ` +
    `If anything in my logs looks concerning, tell me to talk to my doctor.`
  );
}

export default function ExportScreen() {
  const [markdown, setMarkdown] = useState('');
  const [prompt, setPrompt] = useState('');
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);

  const refresh = useCallback(() => {
    const data = getExportData();
    setMarkdown(buildContextMarkdown(data));
    setPrompt(buildCoachPrompt(data));
  }, []);

  useFocusEffect(refresh);

  const copyPrompt = async () => {
    await Clipboard.setStringAsync(prompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportAndShare = async () => {
    try {
      if (!cacheDirectory) {
        return Alert.alert('Unavailable', 'File storage is not available on this device.');
      }
      if (!(await Sharing.isAvailableAsync())) {
        return Alert.alert('Unavailable', 'Sharing is not available on this device.');
      }
      const uri = `${cacheDirectory}diet-coach-context.md`;
      await writeAsStringAsync(uri, markdown);
      await Sharing.shareAsync(uri, {
        mimeType: 'text/markdown',
        dialogTitle: 'Share your AI context file',
      });
      setShared(true);
      setTimeout(() => setShared(false), 2500);
    } catch (e) {
      Alert.alert('Export failed', e instanceof Error ? e.message : 'Unknown error');
    }
  };

  return (
    <View style={common.screen}>
      <ScrollView contentContainerStyle={common.scroll}>
        <Text style={common.h1}>AI Coach</Text>
        <Text style={common.subtitle}>
          Export your profile + last 30 days as a context file, then paste it into the AI chat of
          your choice. Your data stays on your device until you choose to share it.
        </Text>

        <TouchableOpacity style={common.primaryButton} onPress={copyPrompt}>
          <Text style={common.primaryButtonText}>
            {copied ? 'Copied ✓ — paste it into your AI chat' : 'Copy coach setup prompt'}
          </Text>
        </TouchableOpacity>

        <TouchableOpacity style={common.secondaryButton} onPress={exportAndShare}>
          <Text style={common.secondaryButtonText}>
            {shared ? 'Shared ✓' : 'Export & share context file (.md)'}
          </Text>
        </TouchableOpacity>

        <Text style={[common.h2, { marginTop: 20 }]}>Coach prompt preview</Text>
        <View style={common.card}>
          <Text style={styles.mono}>{prompt}</Text>
        </View>

        <Text style={[common.h2, { marginTop: 8 }]}>Context file preview</Text>
        <View style={common.card}>
          <Text style={styles.mono}>{markdown}</Text>
        </View>

        <Text style={styles.disclaimer}>
          Diet Coach is a logging tool, not a medical professional. Nothing here is medical advice.
          Talk to your doctor before changing medications, supplements, or your diet — especially
          with health conditions.
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  mono: {
    fontFamily: 'monospace',
    fontSize: 12,
    color: COLORS.text,
    lineHeight: 18,
  },
  disclaimer: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 8,
    lineHeight: 17,
  },
});
