// Markdown context file and coach prompt for the AI Coach export.
// Pure functions so tests can build the paste block without rendering the screen.
import type { ExportData } from './db/exportData';
import { fmtDateTime } from './datetime';
import { dietPrinciples } from './dietPrinciples';
import { dietDurationLabel, formatDietStart } from './milestones';
import { DIET_LABELS } from './types';

function oneLine(s: string): string {
  return s.replace(/[\r\n]+/g, ' ').trim();
}

/** The Markdown context file: profile + trailing-30-day summary. */
export function buildContextMarkdown(data: ExportData): string {
  const { profile, allergies, conditions, medications, supplements, counts30, rangeLabel } = data;
  const lines: string[] = [];

  lines.push('# KetoKind — AI Context File');
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
  lines.push(`_Exported ${new Date().toLocaleString()} (${tz})_`);
  lines.push('');
  lines.push('## Profile');
  lines.push(`- **Name:** ${oneLine(profile.name) || 'Not specified'}`);
  lines.push(`- **Diet type:** ${DIET_LABELS[profile.diet_type]}`);
  const dietStartFmt = formatDietStart(profile.diet_start);
  const dietDuration = dietDurationLabel(profile.diet_start);
  lines.push(
    `- **Diet started:** ${dietStartFmt}${dietDuration ? ` (${dietDuration} on this diet)` : ''}`,
  );
  lines.push(`- **Age:** ${profile.age != null ? profile.age : 'Not specified'}`);
  lines.push(`- **Sex:** ${profile.sex === 'female' ? 'Female' : profile.sex === 'male' ? 'Male' : 'Not specified'}`);
  lines.push(`- **About me:** ${profile.bio || 'Not specified'}`);
  lines.push(`- **Diet nuances:** ${profile.diet_nuances || 'Not specified'}`);
  lines.push(`- **Goals:** ${profile.goals || 'Not specified'}`);
  lines.push(`- **Allergies:** ${allergies.map((a) => oneLine(a.name)).join(', ') || 'None recorded'}`);
  lines.push(`- **Health conditions:** ${conditions.map((c) => oneLine(c.name)).join(', ') || 'None recorded'}`);
  lines.push(
    `- **Medications:** ${medications.map((m) => `${oneLine(m.name)}${m.dosage ? ` (${m.dosage})` : ''} — ${m.as_needed ? 'as needed' : `${m.times_per_day}x/day`}${m.purpose ? `, for ${m.purpose}` : ''}`).join('; ') || 'None recorded'}`,
  );
  lines.push(
    `- **Supplements:** ${supplements.map((s) => `${oneLine(s.name)}${s.dosage ? ` (${s.dosage})` : ''} — ${s.as_needed ? 'as needed' : `${s.times_per_day}x/day`}${s.purpose ? `, for ${s.purpose}` : ''}`).join('; ') || 'None recorded'}`,
  );
  lines.push('');
  lines.push(`## Last 30 days (${rangeLabel})`);
  lines.push(`- Meals logged: ${counts30.meals}`);
  lines.push(`- Medication doses taken: ${counts30.medsTaken}`);
  lines.push(`- Symptoms logged: ${counts30.symptoms}`);
  lines.push(`- Supplements logged: ${counts30.supplements}`);
  lines.push(`- Weigh-ins: ${counts30.weighIns}`);
  lines.push('');

  if (data.recentMeals.length > 0) {
    lines.push('### Recent meals');
    for (const m of data.recentMeals) {
      const macros =
        m.protein_g == null
          ? ''
          : ` [P ${m.protein_g}g, F ${m.fat_g}g, total C ${m.carbs_g}g, net C ${m.net_carbs_g}g${
              profile.track_calories && m.calories != null ? `, ${m.calories} kcal` : ''
            }${m.macro_source === 'estimated' ? ', estimate' : ''}]`;
      const notes = oneLine(m.notes);
      lines.push(
        `- ${fmtDateTime(m.logged_at)} — ${oneLine(m.meal_type)}: ${oneLine(m.name)}${notes ? ` (${notes})` : ''}${macros}`,
      );
    }
    lines.push('');
  }
  if (data.recentSymptoms.length > 0) {
    lines.push('### Recent symptoms');
    for (const s of data.recentSymptoms) {
      const notes = oneLine(s.notes);
      lines.push(
        `- ${fmtDateTime(s.logged_at)} — ${oneLine(s.name)} (severity ${s.severity}/5)${notes ? ` (${notes})` : ''}`,
      );
    }
    lines.push('');
  }
  if (data.recentSupplements.length > 0) {
    lines.push('### Recent supplements');
    for (const s of data.recentSupplements) {
      const qty = s.quantity > 1 ? ` (took ${s.quantity})` : '';
      const notes = oneLine(s.notes);
      lines.push(`- ${fmtDateTime(s.logged_at)} — ${oneLine(s.name)}${qty}${notes ? ` (${notes})` : ''}`);
    }
    lines.push('');
  }
  if (data.recentMeds.length > 0) {
    lines.push('### Recent medication doses');
    for (const m of data.recentMeds) {
      const name = oneLine(m.medication_name) || 'Deleted medication';
      const qty = m.quantity > 1 ? ` (took ${m.quantity})` : '';
      lines.push(`- ${fmtDateTime(m.taken_at)} — ${name} taken${qty}`);
    }
    lines.push('');
  }
  if (data.recentWeights.length > 0) {
    lines.push('### Recent weigh-ins');
    for (const w of data.recentWeights) {
      lines.push(`- ${fmtDateTime(w.logged_at)} — ${w.weight} lbs`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by KetoKind. Paste this with the coach setup prompt into your preferred AI chat._');
  return lines.join('\n');
}

/** The ready-to-paste prompt that turns any AI chat into the user's coach. */
export function buildCoachPrompt(data: ExportData): string {
  const dietLabel = DIET_LABELS[data.profile.diet_type];
  const principles = dietPrinciples(data.profile.diet_type)
    .map((p, i) => `${i + 1}. ${p}`)
    .join('\n');
  return (
    `You are my ${dietLabel} diet coach. Below is my diet profile ` +
    `(diet type, personal nuances, allergies, health conditions, medications, supplements) and my food, symptom, ` +
    `supplement, medication, and weight logs from the last 30 days.\n\n` +
    `Start by greeting me by name (use my name if it appears in my profile; otherwise just say hello), ` +
    `confirm you have my logs, and ask whether I want insights into my data or have a specific question or concern ` +
    `I want to talk about. Keep every response brief — no long lectures, no unasked-for analysis.\n\n` +
    `Guiding principles:\n` +
    principles +
    `\n\n` +
    `When I ask about my food or macros, estimate protein, fat, and carbs from what's in my logs using typical values for each food. ` +
    `If an entry is too vague to estimate (like "steak" with no portion size), ask me one or two quick questions about portion sizes of the most common items first, then give your best estimate.\n\n` +
    `Important: you are not a medical professional and this is not medical advice. ` +
    `Never tell me to start, stop, or change any medication — only my doctor can do that. ` +
    `If anything in my logs looks concerning, tell me to talk to my doctor.`
  );
}
